version: '0.{build}'
image: Visual Studio 2022
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
configuration:
  - Release
nuget:
  disable_publish_on_pr: true
install:
- ps: |
    Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
    & $env:temp\dotnet-install.ps1 -Architecture x64 -Version '8.0.100' -InstallDir "$env:ProgramFiles\dotnet"
before_build:
  - cmd: dotnet --version
build_script:
  - cmd: dotnet publish ./Content/WebApiTemplate.sln
after_build:
  - cmd: dotnet pack WebApiTemplate.Project.Template.csproj
artifacts:
  - path: '**/*.nupkg'
skip_commits:
  files:
    - '**/*.md'
deploy:
- provider: NuGet
  server: https://www.myget.org/F/webapitemplate/api/v2/package
  on:
    branch: master
  api_key:
    secure: 6xhHSsDvB9arsrSDLuynnbxaVS+BwaoJU96RfQenc5FOnUYvP8SHM6kbvrmpvja2
  skip_symbols: true